# Python para Data Science - Numpy
---

### Importando a biblioteca

In [1]:
import numpy as np

### Importando dados

In [2]:
km = np.loadtxt('data/carros-km.txt')
anos = np.loadtxt('data/carros-anos.txt', dtype = int)
nomes = np.loadtxt('data/carros-nomes.txt', dtype = str, usecols=0)
valor = np.loadtxt('data/carros-valor.txt')
zerokm = np.loadtxt('data/carros-zero-km.txt')


### Criação e manipulação de arrays


In [5]:

# Arrays básicos
array1 = np.array([1, 2, 3])
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))

# Sequências numéricas
arange_array = np.arange(0, 10, 2)  # De 0 a 10 com passo 2
linspace_array = np.linspace(0, 1, 5)  # 5 valores entre 0 e 1

# Array aleatório
random_array = np.random.rand(3, 2)  # Aleatórios uniformes entre 0 e 1

# Exibindo os resultados
array1, zeros_array, ones_array, arange_array, linspace_array, random_array


(array([1, 2, 3]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0.04662769, 0.06513895],
        [0.43033395, 0.67962524],
        [0.31613954, 0.53067097]]))

### Operações matemáticas

In [6]:
# Operações matemáticas
array = np.array([1, 2, 3, 4, 5])
soma = np.sum(array)
media = np.mean(array)
mediana = np.median(array)
variancia = np.var(array)
desvio_padrao = np.std(array)

# Exibindo resultados
soma, media, mediana, variancia, desvio_padrao


(np.int64(15),
 np.float64(3.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(1.4142135623730951))

### Indexação e Slicing

In [7]:
# Indexação e slicing
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

elemento = array[1, 2]  # Elemento na segunda linha, terceira coluna
linha = array[1, :]  # Segunda linha inteira
coluna = array[:, 1]  # Segunda coluna inteira
filtro = array[array > 5]  # Elementos maiores que 5

# Exibindo os resultados
elemento, linha, coluna, filtro


(np.int64(6), array([4, 5, 6]), array([2, 5, 8]), array([6, 7, 8, 9]))

### Manipulação de Formas

In [8]:
# Manipulação de formas
array = np.array([[1, 2, 3], [4, 5, 6]])

reshaped = array.reshape((3, 2))  # Mudando para forma 3x2
achatar = array.flatten()  # Achatar para um vetor
transposta = array.T  # Transposta do array

# Exibindo os resultados
reshaped, achatar, transposta


(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

### Operações com Arrays

In [9]:
# Operações com arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concatenado = np.concatenate([a, b])
empilhado_v = np.vstack([a, b])  # Empilhamento vertical
empilhado_h = np.hstack([a, b])  # Empilhamento horizontal

# Exibindo os resultados
concatenado, empilhado_v, empilhado_h

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

### Estatísticas e Álgebra Linear

In [10]:
# Estatísticas e álgebra linear
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
produto_escalar = np.dot(array1, array2)

matriz = np.array([[1, 2], [3, 4]])
inversa = np.linalg.inv(matriz)  # Inversa da matriz
autovalores, autovetores = np.linalg.eig(matriz)  # Autovalores e autovetores

# Exibindo os resultados
produto_escalar, inversa, autovalores, autovetores


(np.int64(32),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))